# GitHub Pages configuration for Factorial Proposal Generator
title: "Factorial - Gerador de Propostas"
description: "Sistema interno para geração de propostas comerciais da Factorial"
baseurl: "/geradordepropostabr"
url: "https://victorhgutierrez-cloud.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Include files
include:
  - _redirects

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "doc"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO
author: "Factorial Team"
social:
  name: Factorial
  links:
    - https://factorialhr.com

# Analytics (if needed)
# google_analytics: UA-XXXXXXXXX-X

# Comments (if needed)
# disqus:
#   shortname: your-disqus-shortname